using Microsoft.AspNetCore.Identity;
using Npgsql;

// Engangsværktøj: opgraderer den RESTORED (gamle) database in-place til det nye skema
// (med husstande) UDEN at slette data. Al eksisterende data knyttes til én husstand.
//
// Brug:
//   dotnet run -- inspect
//   dotnet run -- migrate "<Husstandsnavn>" "<email>" "<adgangskode>"
// Connection string læses fra env-var NEON.

var conn = Environment.GetEnvironmentVariable("NEON");
if (string.IsNullOrWhiteSpace(conn)) { Console.WriteLine("FEJL: sæt env-var NEON til connection string."); return 1; }

var mode = args.Length > 0 ? args[0] : "inspect";

await using var db = new NpgsqlConnection(conn);
await db.OpenAsync();

async Task<bool> TableExists(string name)
{
    await using var cmd = new NpgsqlCommand(
        "SELECT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name=@n)", db);
    cmd.Parameters.AddWithValue("n", name);
    return (bool)(await cmd.ExecuteScalarAsync())!;
}

async Task<long> Count(string table)
{
    try { await using var c = new NpgsqlCommand($"SELECT COUNT(*) FROM \"{table}\"", db); return (long)(await c.ExecuteScalarAsync())!; }
    catch { return -1; }
}

if (mode == "inspect")
{
    Console.WriteLine("=== Databasens tilstand ===");
    Console.WriteLine($"Households-tabel findes:  {await TableExists("Households")}  (findes den, er login allerede tilføjet)");
    foreach (var t in new[] { "Categories", "Ingredients", "Recipes", "RecipeIngredients", "ItemGroups", "ItemGroupIngredients", "Weeks", "WeekRecipes", "WeekItemGroups", "WeekManualItems", "ShoppingListChecks" })
        Console.WriteLine($"  {t,-22} {await Count(t)} raekker");

    Console.WriteLine("--- Eksempel: opskriftsnavne (saa vi kan se om det er JERES data) ---");
    try
    {
        await using var c = new NpgsqlCommand("SELECT \"Name\" FROM \"Recipes\" ORDER BY \"Name\" LIMIT 25", db);
        await using var r = await c.ExecuteReaderAsync();
        while (await r.ReadAsync()) Console.WriteLine("   - " + r.GetString(0));
    }
    catch (Exception e) { Console.WriteLine("   (kunne ikke laese: " + e.Message + ")"); }

    try
    {
        await using var c = new NpgsqlCommand("SELECT \"MigrationId\" FROM \"__EFMigrationsHistory\" ORDER BY \"MigrationId\"", db);
        await using var r = await c.ExecuteReaderAsync();
        Console.WriteLine("--- Migrations-historik ---");
        while (await r.ReadAsync()) Console.WriteLine("   " + r.GetString(0));
    }
    catch { }
    return 0;
}

if (mode == "migrate")
{
    if (args.Length < 4) { Console.WriteLine("Brug: migrate \"<navn>\" \"<email>\" \"<adgangskode>\""); return 1; }
    var name = args[1];
    var email = args[2].Trim().ToLowerInvariant();
    var password = args[3];

    if (await TableExists("Households")) { Console.WriteLine("STOP: Households findes allerede - ser ud til at vaere migreret. Afbryder."); return 1; }
    if (!await TableExists("Recipes")) { Console.WriteLine("STOP: Recipes-tabellen findes ikke - er databasen restored korrekt?"); return 1; }

    var hash = new PasswordHasher<object>().HashPassword(new object(), password);

    await using var tx = await db.BeginTransactionAsync();
    async Task Exec(string sql, params (string, object)[] ps)
    {
        await using var cmd = new NpgsqlCommand(sql, db, tx);
        foreach (var (k, v) in ps) cmd.Parameters.AddWithValue(k, v);
        await cmd.ExecuteNonQueryAsync();
    }

    // 1) Households-tabel (matcher EF's skema)
    await Exec(@"CREATE TABLE ""Households"" (
        ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
        ""Name"" character varying(150) NOT NULL,
        ""Email"" character varying(200) NOT NULL,
        ""PasswordHash"" text NOT NULL,
        ""CreatedUtc"" timestamp with time zone NOT NULL,
        CONSTRAINT ""PK_Households"" PRIMARY KEY (""Id""));");
    await Exec(@"CREATE UNIQUE INDEX ""IX_Households_Email"" ON ""Households"" (""Email"");");

    // 2) Opret din husstand
    int hid;
    await using (var cmd = new NpgsqlCommand(
        @"INSERT INTO ""Households"" (""Name"",""Email"",""PasswordHash"",""CreatedUtc"")
          VALUES (@n,@e,@p, now() at time zone 'utc') RETURNING ""Id"";", db, tx))
    {
        cmd.Parameters.AddWithValue("n", name);
        cmd.Parameters.AddWithValue("e", email);
        cmd.Parameters.AddWithValue("p", hash);
        hid = (int)(await cmd.ExecuteScalarAsync())!;
    }
    Console.WriteLine($"Oprettede husstand '{name}' med Id={hid}");

    // 3) HouseholdId paa eksisterende tabeller (nullable -> backfill -> not null + FK)
    foreach (var t in new[] { "ItemGroups", "Recipes", "Weeks" })
    {
        await Exec($@"ALTER TABLE ""{t}"" ADD COLUMN ""HouseholdId"" integer;");
        await Exec($@"UPDATE ""{t}"" SET ""HouseholdId"" = @h;", ("h", hid));
        await Exec($@"ALTER TABLE ""{t}"" ALTER COLUMN ""HouseholdId"" SET NOT NULL;");
        await Exec($@"ALTER TABLE ""{t}"" ADD CONSTRAINT ""FK_{t}_Households_HouseholdId""
                      FOREIGN KEY (""HouseholdId"") REFERENCES ""Households""(""Id"") ON DELETE CASCADE;");
    }
    await Exec(@"CREATE INDEX ""IX_ItemGroups_HouseholdId"" ON ""ItemGroups"" (""HouseholdId"");");
    await Exec(@"CREATE INDEX ""IX_Recipes_HouseholdId"" ON ""Recipes"" (""HouseholdId"");");

    // 4) Uge-unik-indeks: fra (Year,WeekNumber) til (HouseholdId,Year,WeekNumber)
    await Exec(@"DROP INDEX IF EXISTS ""IX_Weeks_Year_WeekNumber"";");
    await Exec(@"CREATE UNIQUE INDEX ""IX_Weeks_HouseholdId_Year_WeekNumber"" ON ""Weeks"" (""HouseholdId"",""Year"",""WeekNumber"");");

    // 5) Ret EF-migrations-historik saa den nye kode ikke proever at gen-oprette tabeller
    await Exec(@"DELETE FROM ""__EFMigrationsHistory"" WHERE ""MigrationId"" LIKE '%_InitialCreate';");
    await Exec(@"INSERT INTO ""__EFMigrationsHistory"" (""MigrationId"",""ProductVersion"") VALUES ('20260705085622_InitialCreate','10.0.9');");

    await tx.CommitAsync();

    Console.WriteLine("=== FAERDIG. Alt data knyttet til din husstand: ===");
    Console.WriteLine($"  Recipes:    {await Count("Recipes")}");
    Console.WriteLine($"  ItemGroups: {await Count("ItemGroups")}");
    Console.WriteLine($"  Weeks:      {await Count("Weeks")}");
    return 0;
}

if (mode == "addhousehold")
{
    if (args.Length < 4) { Console.WriteLine("Brug: addhousehold \"<navn>\" \"<login>\" \"<adgangskode>\""); return 1; }
    var name = args[1];
    var email = args[2].Trim().ToLowerInvariant();
    var password = args[3];

    if (!await TableExists("Households")) { Console.WriteLine("STOP: Households-tabel findes ikke (kør 'migrate' først)."); return 1; }

    await using (var chk = new NpgsqlCommand("SELECT COUNT(*) FROM \"Households\" WHERE \"Email\"=@e", db))
    {
        chk.Parameters.AddWithValue("e", email);
        if ((long)(await chk.ExecuteScalarAsync())! > 0) { Console.WriteLine($"STOP: login '{email}' findes allerede."); return 1; }
    }

    var hash = new PasswordHasher<object>().HashPassword(new object(), password);
    await using var cmd = new NpgsqlCommand(
        @"INSERT INTO ""Households"" (""Name"",""Email"",""PasswordHash"",""CreatedUtc"")
          VALUES (@n,@e,@p, now() at time zone 'utc') RETURNING ""Id"";", db);
    cmd.Parameters.AddWithValue("n", name);
    cmd.Parameters.AddWithValue("e", email);
    cmd.Parameters.AddWithValue("p", hash);
    var id = (int)(await cmd.ExecuteScalarAsync())!;
    Console.WriteLine($"OK: oprettede husstand '{name}' (login '{email}') med Id={id}. Starter uden data.");
    return 0;
}

Console.WriteLine("Ukendt mode. Brug 'inspect', 'migrate' eller 'addhousehold'.");
return 1;
